### ISSUE TITLE
zwave events are duplicated on each deployment.

### ISSUE THREAD

**Issue by Stubbs** [OpenZWave/node-red-contrib-openzwave#15]
Whenever I deploy a node-red flow I start to get duplicated events through from the openzwave node.

Each time I re-deploy another set of events gets added, like this:

```
{"nodeid":7,"notification":3,"help":"Notification - Node Awake","uuid":"b827ebfc385b-0xd461202f-7"}
{"nodeid":7,"notification":4,"help":"Notification - Node Asleep","uuid":"b827ebfc385b-0xd461202f-7"}
```

redeploy

```
{"nodeid":7,"notification":3,"help":"Notification - Node Awake","uuid":"b827ebfc385b-0xd461202f-7"}
{"nodeid":7,"notification":3,"help":"Notification - Node Awake","uuid":"b827ebfc385b-0xd461202f-7"}
{"nodeid":7,"notification":4,"help":"Notification - Node Asleep","uuid":"b827ebfc385b-0xd461202f-7"}
{"nodeid":7,"notification":4,"help":"Notification - Node Asleep","uuid":"b827ebfc385b-0xd461202f-7"}
```

redeploy

```
{"nodeid":7,"notification":3,"help":"Notification - Node Awake","uuid":"b827ebfc385b-0xd461202f-7"}
{"nodeid":7,"notification":3,"help":"Notification - Node Awake","uuid":"b827ebfc385b-0xd461202f-7"}
{"nodeid":7,"notification":3,"help":"Notification - Node Awake","uuid":"b827ebfc385b-0xd461202f-7"}
{"nodeid":7,"notification":4,"help":"Notification - Node Asleep","uuid":"b827ebfc385b-0xd461202f-7"}
{"nodeid":7,"notification":4,"help":"Notification - Node Asleep","uuid":"b827ebfc385b-0xd461202f-7"}
{"nodeid":7,"notification":4,"help":"Notification - Node Asleep","uuid":"b827ebfc385b-0xd461202f-7"}
```

etc.

**Comment by kmoughon** [comment]
I too am seeing this same error. Is there any information i can provide to help with the troubleshooting?

**Comment by bpillatsch** [comment]
This may be related... [https://github.com/OpenZWave/node-openzwave-shared/issues/59](https://github.com/OpenZWave/node-openzwave-shared/issues/59) I'll look this over tomorrow.

**Comment by kmoughon** [comment]
Looks very plausible. My first guess would be add that remove all listeners to the node-red on close() event handlers, in 10-zwave.js line 278 and 313. I will have a chance to try it out later today if you don't get to it. Thanks for looking into this!

**Comment by kmoughon** [comment]
Nevermind... my suggestion is not relevant, i was mistaken about the structure.

**Comment by kmoughon** [comment]
Any updates or thoughts?

**Comment by pfennich** [comment]
I was facing the same problem and found how to solve the issue

ZWaveController, ZWaveIn and ZWaveOut are listening to a Node-Red event Close that is never triggered by Node-Red.

Looking at the [Node-Red API Reference](https://github.com/node-red/node-red/wiki/API-Reference), there is no refence to a Close event but node.close() to implement for any required clean up .

I added the following changes...

// ZWaveController add
                this.close = function() {
                     node.log('zwave-controller: close');
                     // controller should also unbind from the C++ addon
                        if (ozwDriver) ozwDriver.removeAllListeners();
                }
//ZWaveIn
                this.close = function() {
                        // set zwave node status as disconnected
                        node.status({fill:"red",shape:"ring",text:"disconnected"});
                        // remove all event subscriptions for this node
                        zwunsubscribe(this);
                        node.log('zwave-in: close');
                }

//ZWaveOut
                   this.close = function(){
                        // set zwave node status as disconnected
                        node.status({fill:"red",shape:"ring",text:"disconnecting"});
                        // remove all event subscriptions for this node
                        zwunsubscribe(this);
                        node.log('zwave-out: close');
                }

**Comment by kmoughon** [comment]
Thanks for the suggestion, I don't seem to be having any luck. I have confirmed that the events you suggested to add fire via logging, but don't seem to be solving the issue. What version of nodejs and node-red are you using?

**Comment by pfennich** [comment]
Forgot to mention and I think this is the main issue..
In ZWaveController constructor included /*=== OpenZWave events ==*/ block into the if(!ozwDriver ) block, as there is no reason to register for the list of events for every deployement.

                // so we only get to initialise one single OZW driver (a lengthy process)
                if (!ozwDriver) {
                        ozwDriver = new OpenZWave({
                                Logging:       debug,
                                ConsoleOutput: debug,
                                QueueLogLevel: 6
                        });
                //****pfennich remove     }

                /* =============== OpenZWave events ================== */
                Object.keys(ozwEvents).forEach(function (evt) {
                        if (debug) console.log(node.name+' addListener ' + evt);
                        ozwDriver.on(evt, ozwEvents[evt]);
                })
                }  //*****pfennich add

**Comment by ekarak** [comment]
Hello all and thank you for your feedback.

Unfortunately I cannot replicate this issue (no time and/or spare zwave controller), so I need your help. I've just committed pfennich's fix above to a branch . Please download [the 10-zwave.js file](https://github.com/OpenZWave/node-red-contrib-openzwave/raw/bugfix/issue15/10-zwave.js) and replace this with the one that comes from the npm installation. If it solves your problem, I'll merge and release a new version.

Thanks!

**Comment by kmoughon** [comment]
I can confirm this fix works, I used the patched file as a direct replacement as you suggested. Only interesting thing was that a simple node-red restart didn't fix the problem, but as soon as i modified a flow and redeployed, the duplicate messages were gone. I assume this is from the modified methods eliminating the duplicate event subscriptions from the underlying open zwave lib. 

Thanks very much for your help guys! If there is anything you want to know about my config let me know.

**Comment by ekarak** [comment]
thanks, resolving
