### ISSUE TITLE
Uncaught exception: Reference error: msg is undefined.

### ISSUE THREAD

**Issue by Stubbs** [OpenZWave/node-red-contrib-openzwave#16]
This error is causing my node-red to restart when it receives a zwave message via a zwave-in node.

```
node-red-0 28 Dec 02:10:50 - ReferenceError: msg is not defined
    at EventEmitter.nodeEvent (/home/pi/.node-red/node_modules/node-red-contrib-openzwave/10-zwave.js:217:12)
    at EventEmitter.emit (events.js:106:17)
    at addonModule.Emitter.emit (/home/pi/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared/lib/openzwave-shared.js:39:5)
```

Looking at the source for 10-zwave.js I can't see where msg will have been initialised?

**Comment by Stubbs** [comment]
After a few restarts because of this error, it starts to work, is `msg` in the global scope?

**Comment by ekarak** [comment]
You're so right, this `msg` should be the help string passed on from the callback. I've just committed version 1.1.6 with the [required fix](https://github.com/OpenZWave/node-red-contrib-openzwave/commit/488e703d10afec1b798fac9b19c8ceb2a36089ff).
Thank you very much and season's greetings!

**Comment by Stubbs** [comment]
I've updated to this version  on the library but now node-red segfaults on startup. I've narrowed it down to this library by removing it from node_modules and confirming that node-red starts up.

**Comment by Stubbs** [comment]
I've removed the node module & the node_gyp directory and re-installed and I'm still getting the segfault.

**Comment by ekarak** [comment]
Have you tried reinstalling openzwave?
Στις 31 Δεκ 2015 9:01 μ.μ., ο χρήστης "Stuart Grimshaw" <
notifications@github.com> έγραψε:

**Comment by Stubbs** [comment]
Yes, I fetched the latest version from Github first & re-installed.

**Comment by Stubbs** [comment]
It's the call to 

```
var addonModule = require(addonFileName);
```

in `openzwave-shared.js` that's causing the segfault. It's a binary file so I can't trace it any further in ...

**Comment by ekarak** [comment]
Could you please run node inside a gdb session?
`gdb --args node test.js`
Then, start the debugger with "r" and when the error is raised, run "bt"
to get a stacktrace. Then, please post the stacktrace here.
Στις 1 Ιαν 2016 8:33 μ.μ., ο χρήστης "Stuart Grimshaw" <
notifications@github.com> έγραψε:

**Comment by Stubbs** [comment]
```
pi@rpib ~/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared $ gdb --args node test.js
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/bin/node...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/local/bin/node test.js

Program received signal SIGILL, Illegal instruction.
0xb6fe8acc in ?? () from /lib/ld-linux-armhf.so.3
(gdb) bt
#0  0xb6fe8acc in ?? () from /lib/ld-linux-armhf.so.3
#1  0x00000000 in ?? ()
```

Hope that helps ...

**Comment by ekarak** [comment]
This looks like the error is raised from the system's dynamic linker. I
suspect something's wrong with your compiler.
Στις 2 Ιαν 2016 12:15 π.μ., ο χρήστης "Stuart Grimshaw" <
notifications@github.com> έγραψε:

**Comment by Stubbs** [comment]
You're right, looks like the SD card is having issues, even apt-cache is segfaulting. I've moved the Razberry to a new Pi & I've encountered different issues that I'll post to the mailing list because I don't think it's a bug in the code.
